### ISSUE TITLE
module.exports = { ... } does not seem to generate any docs

### ISSUE THREAD

**Issue by gitgrimbo** [lcodes/esdoc-node#2]
Code of the following form does not seem to generate any docs.  The source file is present on the `source.html` page, but none of the `a`, `b`, `c`, identifiers are associated with the source file (on the `source.html` page), and no function reference appears in the left-hand menu.

```
function a() {}
function b() {}
function c() {}

module.exports = {
  a,
  b,
  c,
};
```

**Comment by lcodes** [comment]
I just merged a pull request fixing this issue. I tested locally with your snippet and all three functions appear in the generated documentation!

1.0.1 has been pushed to the npm registry!
